import {
  Product,
  Category,
  ServiceItem,
  Customer,
  Sale,
  Expense,
  PortfolioProject,
  WebsiteContent,
  StoreSettings,
  StockMovement,
} from '../types';

export const initialWebsiteContent: WebsiteContent = {
  hero_headline: 'Fotocopy, Printing & ATK Lebih Mudah dalam Satu Tempat.',
  hero_subheadline:
    'Solusi kebutuhan dokumen, printing, alat tulis dan layanan digital untuk pelajar, masyarakat, UMKM dan bisnis.',
  hero_badge: 'Buka Setiap Hari • Layanan Cepat & Rapi',
  business_tagline: 'Fotocopy • Printing • ATK',
  whatsapp_number: '6289609312205',
  phone_number: '0838-9751-4568',
  email: 'hidayatressa@gmail.com',
  address: 'Jl.Pasir Jengkol 1 Depan SDN Pasir Jengkol 3, Majalaya',
  city: 'Karawang, Indonesia',
  maps_embed_url: 'https://maps.app.goo.gl/tJbr7wqupv8rEKim7',
  business_hours_weekday: 'Senin - Jumat: 07.30 - 21.00 WIB',
  business_hours_weekend: 'Sabtu - Minggu: 08.00 - 18.00 WIB',
  announcement_banner_enabled: true,
  announcement_banner_text:
    '📢 Butuh print dokumen mendadak? Kirim file sekarang via WhatsApp, kami siapkan dan langsung siap ambil!',
  digital_solutions_intro:
    'Selain layanan printing dan ATK, After Project juga membantu UMKM dan bisnis membangun solusi digital sederhana sesuai kebutuhan.',
  why_us_points: [
    {
      title: 'Pelayanan Cepat',
      description: 'Mesin fotocopy high-speed dan printer laser responsif untuk memangkas waktu tunggu Anda.',
      icon: 'Zap',
    },
    {
      title: 'Harga Transparan',
      description: 'Tarif cetak dan fotocopy jelas tanpa biaya tersembunyi, cocok untuk kantong pelajar & anggaran kantor.',
      icon: 'Receipt',
    },
    {
      title: 'Kebutuhan ATK Lengkap',
      description: 'Tersedia pulpen, buku, kertas rim, map arsip, hingga perlengkapan kantor siap pakai.',
      icon: 'PackageCheck',
    },
    {
      title: 'Printing & Fotocopy Presisi',
      description: 'Hasil cetak tajam, warna akurat, serta opsi bolak-balik (duplex) rapi dan presisi.',
      icon: 'Printer',
    },
    {
      title: 'Bisa Kirim File via WhatsApp',
      description: 'Tak perlu antri lama di toko, cukup kirim PDF atau file gambar lewat WA lalu ambil saat siap.',
      icon: 'MessageCircle',
    },
    {
      title: 'Melayani Individu & UMKM',
      description: 'Menerima fotocopy 1 lembar KTP hingga cetak ribuan proposal, modul sekolah, atau invoice usaha.',
      icon: 'Users',
    },
  ],
};

export const initialStoreSettings: StoreSettings = {
  store_name: 'AFTER PROJECT',
  main_tagline: 'Fotocopy • Printing • ATK',
  sub_tagline: 'Solusi Dokumen, Percetakan & Kebutuhan Usaha',
  address: 'Jl.Pasir Jengkol 1 Depan SDN Pasir Jengkol 3, Majalaya',
  phone: '0838-9751-4568',
  whatsapp: '6289609312205',
  qris_merchant_name: 'AFTER PROJECT STORE',
  bank_name: 'BCA / Mandiri / BRI',
  bank_account_number: '8830-1234-5678',
  bank_account_holder: 'AFTER PROJECT INDONESIA',
  receipt_footer_note: 'Terima kasih atas kunjungan Anda! Simpan struk ini sebagai bukti pembayaran yang sah.',
  demo_mode: false,
};

export const demoCategories: Category[] = [
  { id: 'cat-1', name: 'Alat Tulis', slug: 'alat-tulis', icon: 'PenTool', type: 'atk', description: 'Pulpen, pensil, penghapus, penggaris, spidol' },
  { id: 'cat-2', name: 'Buku & Kertas', slug: 'buku-kertas', icon: 'BookOpen', type: 'atk', description: 'Buku tulis, buku kas, kertas HVS A4/F4, folio bergaris' },
  { id: 'cat-3', name: 'Map & Arsip', slug: 'map-arsip', icon: 'Folder', type: 'atk', description: 'Map snelhecter, stopmap folio, clear holder, binder' },
  { id: 'cat-4', name: 'Perlengkapan Sekolah', slug: 'perlengkapan-sekolah', icon: 'GraduationCap', type: 'atk', description: 'Tipe-x, gunting, lem kertas, jangka, sampul' },
  { id: 'cat-5', name: 'Perlengkapan Kantor', slug: 'perlengkapan-kantor', icon: 'Briefcase', type: 'atk', description: 'Stapler, isi staples, klip kertas, lakban, cutter' },
  { id: 'cat-6', name: 'Printing Supplies', slug: 'printing-supplies', icon: 'Layers', type: 'atk', description: 'Plastik laminating, mika jilid, spiral kawat, buffalo' },
  { id: 'cat-7', name: 'Layanan Fotocopy', slug: 'layanan-fotocopy', icon: 'Copy', type: 'service', description: 'Fotocopy A4, F4, A3, KTP, dan bolak-balik' },
  { id: 'cat-8', name: 'Layanan Printing', slug: 'layanan-printing', icon: 'Printer', type: 'service', description: 'Print hitam-putih dan warna tajam' },
  { id: 'cat-9', name: 'Finishing & Dokumen', slug: 'finishing-dokumen', icon: 'FileCheck', type: 'service', description: 'Laminating, scan, jilid lakban, spiral, dan cutting' },
];

export const demoServices: ServiceItem[] = [
  {
    id: 'srv-1',
    service_name: 'Fotocopy A4 (1 Sisi)',
    category: 'Fotocopy',
    unit: 'lembar',
    cost: 120,
    selling_price: 350,
    description: 'Fotocopy kertas HVS 70-75 gsm hitam putih satu muka, hasil tajam.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-2',
    service_name: 'Fotocopy F4 / Folio (1 Sisi)',
    category: 'Fotocopy',
    unit: 'lembar',
    cost: 130,
    selling_price: 400,
    description: 'Fotocopy kertas F4 HVS standar satu muka, cocok untuk surat dan berkas dinas.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-3',
    service_name: 'Fotocopy Bolak-Balik (A4 / F4)',
    category: 'Fotocopy',
    unit: 'lembar',
    cost: 200,
    selling_price: 600,
    description: 'Fotocopy dua muka hemat kertas dan rapi untuk modul atau dokumen tebal.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-4',
    service_name: 'Fotocopy KTP / SIM / Kartu Identitas',
    category: 'Fotocopy',
    unit: 'lembar',
    cost: 150,
    selling_price: 500,
    description: 'Fotocopy KTP bolak-balik sejajar rapi atau isi 1 lembar 4-8 kartu.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-5',
    service_name: 'Print Hitam Putih (B/W) Teks',
    category: 'Print B/W',
    unit: 'lembar',
    cost: 250,
    selling_price: 500,
    description: 'Cetak dokumen teks, tugas sekolah, skripsi hitam putih laser/inkjet jernih.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-6',
    service_name: 'Print Warna Teks / Diagram Ringan',
    category: 'Print Color',
    unit: 'lembar',
    cost: 500,
    selling_price: 1500,
    description: 'Print teks dengan kop surat, logo warna, atau diagram statistik.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-7',
    service_name: 'Print Full Color / Gambar / Foto',
    category: 'Print Color',
    unit: 'lembar',
    cost: 1200,
    selling_price: 3000,
    description: 'Cetak full halaman warna pekat, gambar tugas, proposal atau poster A4.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-8',
    service_name: 'Scan Dokumen ke PDF / JPG',
    category: 'Scan',
    unit: 'halaman',
    cost: 200,
    selling_price: 1000,
    description: 'Scan resolusi tinggi 300-600 DPI, langsung dikirim via WhatsApp atau Email.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-9',
    service_name: 'Laminating Panas Presisi (A4 / F4)',
    category: 'Laminating',
    unit: 'lembar',
    cost: 1500,
    selling_price: 5000,
    description: 'Plastik laminating tebal anti-air, lindungi ijazah, sertifikat & kartu penting.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-10',
    service_name: 'Jilid Lakban & Mika Standar',
    category: 'Finishing',
    unit: 'buku',
    cost: 1200,
    selling_price: 4000,
    description: 'Cover mika bening depan, kertas buffalo warna belakang, lakban hitam rapi.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-11',
    service_name: 'Cutting / Potong Kertas Massal',
    category: 'Cutting',
    unit: 'rim',
    cost: 1000,
    selling_price: 5000,
    description: 'Pemotongan presisi menggunakan mesin pemotong kertas tuas baja.',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoProducts: Product[] = [
  {
    id: 'prd-1',
    barcode: '89923451101',
    sku: 'ATK-PEN-01',
    name: 'Pulpen Standard AE7 0.5mm Hitam',
    category_id: 'cat-1',
    purchase_price: 2200,
    selling_price: 3500,
    stock: 84,
    minimum_stock: 20,
    unit: 'pcs',
    description: 'Pulpen bolpoin terlaris, tinta hitam pekat, ujung jarum lancar tidak macet.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-2',
    barcode: '89923451102',
    sku: 'ATK-PEN-02',
    name: 'Pulpen Gel Kenko K-1 0.5mm',
    category_id: 'cat-1',
    purchase_price: 3800,
    selling_price: 6000,
    stock: 45,
    minimum_stock: 15,
    unit: 'pcs',
    description: 'Pulpen gel tinta cepat kering, pegangan karet nyaman untuk menulis lama.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-3',
    barcode: '89923451103',
    sku: 'ATK-PNS-01',
    name: 'Pensil 2B Faber-Castell Ujian Asli',
    category_id: 'cat-1',
    purchase_price: 3500,
    selling_price: 5000,
    stock: 62,
    minimum_stock: 20,
    unit: 'pcs',
    description: 'Pensil standar komputer OMR untuk ujian nasional dan sekolah.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-4',
    barcode: '89923451104',
    sku: 'ATK-PHS-01',
    name: 'Penghapus Faber-Castell Hitam Dust-Free',
    category_id: 'cat-1',
    purchase_price: 3000,
    selling_price: 4500,
    stock: 38,
    minimum_stock: 15,
    unit: 'pcs',
    description: 'Penghapus tanpa debu sisa kotoran banyak, tidak merobek kertas.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-5',
    barcode: '89923451105',
    sku: 'ATK-TPX-01',
    name: 'Correction Tape Joyko CT-522 (Kertas Tipe-X)',
    category_id: 'cat-4',
    purchase_price: 5000,
    selling_price: 8000,
    stock: 29,
    minimum_stock: 10,
    unit: 'pcs',
    description: 'Pita koreksi praktis tidak belepotan, bisa langsung ditulis kembali.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-6',
    barcode: '89923451106',
    sku: 'KRT-HVS-A4',
    name: 'Kertas HVS Sinar Dunia (SiDU) A4 75 Gsm (1 Rim)',
    category_id: 'cat-2',
    purchase_price: 46000,
    selling_price: 54000,
    stock: 24,
    minimum_stock: 10,
    unit: 'rim',
    description: '1 rim isi 500 lembar, putih bersih, cocok untuk print dokumen & skripsi.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-7',
    barcode: '89923451107',
    sku: 'KRT-HVS-F4',
    name: 'Kertas HVS PaperOne F4/Folio 75 Gsm (1 Rim)',
    category_id: 'cat-2',
    purchase_price: 51000,
    selling_price: 59000,
    stock: 18,
    minimum_stock: 8,
    unit: 'rim',
    description: 'Kertas folio premium bebas macet mesin, kemasan rapi 500 lembar.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-8',
    barcode: '89923451108',
    sku: 'BKU-TLS-38',
    name: 'Buku Tulis KIKY 38 Lembar',
    category_id: 'cat-2',
    purchase_price: 3200,
    selling_price: 4500,
    stock: 70,
    minimum_stock: 20,
    unit: 'pcs',
    description: 'Buku tulis garis rapi dengan motif sampul menarik untuk siswa.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-9',
    barcode: '89923451109',
    sku: 'MAP-SNEL-01',
    name: 'Map Snelhecter Plastik Joyko Folio',
    category_id: 'cat-3',
    purchase_price: 3000,
    selling_price: 5000,
    stock: 52,
    minimum_stock: 15,
    unit: 'pcs',
    description: 'Map jepit dokumen dengan pengait plastik kuat aneka warna pilihan.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-10',
    barcode: '89923451110',
    sku: 'MAP-STOP-01',
    name: 'Stopmap Folio Kertas Buffalo Warna',
    category_id: 'cat-3',
    purchase_price: 1200,
    selling_price: 2500,
    stock: 110,
    minimum_stock: 30,
    unit: 'pcs',
    description: 'Map kertas tebal untuk berkas lamaran kerja, kantor, dan ujian.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-11',
    barcode: '89923451111',
    sku: 'ATK-STP-10',
    name: 'Stapler Joyko HD-10 + Isi Staples',
    category_id: 'cat-5',
    purchase_price: 11000,
    selling_price: 16000,
    stock: 6, // Low stock demo
    minimum_stock: 10,
    unit: 'set',
    description: 'Stapler genggam ukuran standar No. 10 tahan karat dengan 1 kotak isi.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-12',
    barcode: '89923451112',
    sku: 'ATK-LKB-01',
    name: 'Lakban Hitam Kain Daimaru 2 Inch (48mm)',
    category_id: 'cat-5',
    purchase_price: 14000,
    selling_price: 19000,
    stock: 5, // Low stock demo
    minimum_stock: 8,
    unit: 'roll',
    description: 'Lakban jilid buku super rekat, tidak mudah lepas dan tahan lembap.',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoCustomers: Customer[] = [
  {
    id: 'cst-1',
    name: 'Ibu Ratna (Guru SMPN 1)',
    phone: '0813-9876-5432',
    whatsapp: '6281398765432',
    address: 'Jl. Pemuda No. 12',
    customer_type: 'SCHOOL',
    notes: 'Rutin fotocopy soal ujian dan modul pelajaran bulanan.',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'cst-2',
    name: 'Bagas Pratama (Mahasiswa)',
    phone: '0857-1122-3344',
    whatsapp: '6285711223344',
    address: 'Kos Pondok Asri No. 4',
    customer_type: 'STUDENT',
    notes: 'Sering print laporan akhir dan jilid skripsi.',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'cst-3',
    name: 'Warung Bu Dewi (UMKM)',
    phone: '0821-4455-6677',
    whatsapp: '6282144556677',
    address: 'Pasar Baru Kios B-12',
    customer_type: 'UMKM',
    notes: 'Pesan nota kasir rangkap, stiker label produk, dan konsultasi website profil warung.',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'cst-4',
    name: 'PT Mitra Cahaya Abadi',
    phone: '021-7788-9900',
    whatsapp: '6281800998877',
    address: 'Kawasan Niaga Sentra Blok C',
    customer_type: 'COMPANY',
    notes: 'Kebutuhan ATK bulanan kantor dan cetak laporan tahunan.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const demoExpenses: Expense[] = [
  {
    id: 'exp-1',
    date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    category: 'Kertas',
    description: 'Restok 10 rim kertas HVS SiDU A4 75gsm',
    amount: 460000,
    notes: 'Dari distributor kertas grosir',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'exp-2',
    date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    category: 'Toner & Tinta',
    description: 'Beli toner bubuk fotocopy Canon IR 1 kg',
    amount: 175000,
    notes: 'Untuk mesin fotocopy utama',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'exp-3',
    date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    category: 'Listrik & Utilitas',
    description: 'Token listrik PLN operasional toko',
    amount: 250000,
    notes: 'Daya 3500 VA',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'exp-4',
    date: new Date(Date.now() - 12 * 86400000).toISOString().split('T')[0],
    category: 'Perawatan Mesin',
    description: 'Servis berkala roll penarik kertas & pembersihan scanner',
    amount: 120000,
    notes: 'Teknisi lokal',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
];

export const demoPortfolioProjects: PortfolioProject[] = [
  {
    id: 'port-1',
    title: 'Sistem Kasir & Inventori Toko Bahan Bangunan',
    category: 'Point of Sale & Stock',
    client: 'TB Usaha Berkah (UMKM Lokal)',
    description:
      'Aplikasi web POS modern berbasis barcode scanner untuk kasir dan pemantauan stok besi, semen, dan cat secara real-time dari HP pemilik.',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'IndexedDB / Cloud Sync'],
    status: 'completed',
    is_demo: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'port-2',
    title: 'Website Profil & Katalog Menu Warung Kopi & Resto',
    category: 'Website Usaha',
    client: 'Kopi Ruang Temu',
    description:
      'Website responsif ramah mobile dengan menu interaktif, integrasi pemesanan WhatsApp langsung, dan optimasi peta lokasi Google Maps.',
    technologies: ['Vite', 'Tailwind CSS', 'WhatsApp Order Flow', 'SEO Lokal'],
    status: 'completed',
    is_demo: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'port-3',
    title: 'Aplikasi Absensi & Pencatatan Kas Sekolah',
    category: 'Custom Web Application',
    client: 'SMK Karya Mandiri',
    description:
      'Dashboard manajemen sederhana untuk rekap iuran praktikum siswa, absensi kegiatan, dan cetak laporan PDF berkala.',
    technologies: ['React', 'Export Excel / PDF', 'Authentication', 'Responsive Dashboard'],
    status: 'completed',
    is_demo: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const demoSales: Sale[] = [
  {
    id: 'sale-1',
    invoice_number: 'INV-20260921-001',
    customer_id: 'cst-2',
    customer_name: 'Bagas Pratama (Mahasiswa)',
    subtotal: 31000,
    discount: 1000,
    total: 30000,
    payment_method: 'QRIS',
    payment_status: 'PAID',
    notes: 'Print tugas & fotocopy rangkuman ujian',
    cashier_name: 'Admin Kasir',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    items: [
      {
        id: 'item-1',
        sale_id: 'sale-1',
        item_type: 'SERVICE',
        service_id: 'srv-5',
        description: 'Print Hitam Putih (B/W) Teks',
        quantity: 20,
        unit_price: 500,
        cost_price: 250,
        subtotal: 10000,
      },
      {
        id: 'item-2',
        sale_id: 'sale-1',
        item_type: 'SERVICE',
        service_id: 'srv-1',
        description: 'Fotocopy A4 (1 Sisi)',
        quantity: 20,
        unit_price: 350,
        cost_price: 120,
        subtotal: 7000,
      },
      {
        id: 'item-3',
        sale_id: 'sale-1',
        item_type: 'SERVICE',
        service_id: 'srv-10',
        description: 'Jilid Lakban & Mika Standar',
        quantity: 2,
        unit_price: 4000,
        cost_price: 1200,
        subtotal: 8000,
      },
      {
        id: 'item-4',
        sale_id: 'sale-1',
        item_type: 'PRODUCT',
        product_id: 'prd-1',
        description: 'Pulpen Standard AE7 0.5mm Hitam',
        quantity: 1,
        unit_price: 3500,
        cost_price: 2200,
        subtotal: 3500,
      },
      {
        id: 'item-5',
        sale_id: 'sale-1',
        item_type: 'PRODUCT',
        product_id: 'prd-10',
        description: 'Stopmap Folio Kertas Buffalo Warna',
        quantity: 1,
        unit_price: 2500,
        cost_price: 1200,
        subtotal: 2500,
      },
    ],
  },
  {
    id: 'sale-2',
    invoice_number: 'INV-20260921-002',
    customer_id: 'cst-1',
    customer_name: 'Ibu Ratna (Guru SMPN 1)',
    subtotal: 70000,
    discount: 5000,
    total: 65000,
    payment_method: 'CASH',
    payment_status: 'PAID',
    cash_received: 100000,
    cash_change: 35000,
    notes: 'Fotocopy soal latihan 200 lembar bolak-balik',
    cashier_name: 'Admin Kasir',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    items: [
      {
        id: 'item-201',
        sale_id: 'sale-2',
        item_type: 'SERVICE',
        service_id: 'srv-3',
        description: 'Fotocopy Bolak-Balik (A4 / F4)',
        quantity: 100,
        unit_price: 600,
        cost_price: 200,
        subtotal: 60000,
      },
      {
        id: 'item-202',
        sale_id: 'sale-2',
        item_type: 'PRODUCT',
        product_id: 'prd-9',
        description: 'Map Snelhecter Plastik Joyko Folio',
        quantity: 2,
        unit_price: 5000,
        cost_price: 3000,
        subtotal: 10000,
      },
    ],
  },
  {
    id: 'sale-3',
    invoice_number: 'INV-20260920-001',
    customer_name: 'Pelanggan Walk-In',
    subtotal: 23500,
    discount: 0,
    total: 23500,
    payment_method: 'CASH',
    payment_status: 'PAID',
    cash_received: 50000,
    cash_change: 26500,
    notes: 'Laminating sertifikat & pulpen',
    cashier_name: 'Admin Kasir',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    items: [
      {
        id: 'item-301',
        sale_id: 'sale-3',
        item_type: 'SERVICE',
        service_id: 'srv-9',
        description: 'Laminating Panas Presisi (A4 / F4)',
        quantity: 3,
        unit_price: 5000,
        cost_price: 1500,
        subtotal: 15000,
      },
      {
        id: 'item-302',
        sale_id: 'sale-3',
        item_type: 'PRODUCT',
        product_id: 'prd-5',
        description: 'Correction Tape Joyko CT-522 (Kertas Tipe-X)',
        quantity: 1,
        unit_price: 8000,
        cost_price: 5000,
        subtotal: 8000,
      },
      {
        id: 'item-303',
        sale_id: 'sale-3',
        item_type: 'SERVICE',
        service_id: 'srv-4',
        description: 'Fotocopy KTP / SIM / Kartu Identitas',
        quantity: 1,
        unit_price: 500,
        cost_price: 150,
        subtotal: 500,
      },
    ],
  },
];

export const demoStockMovements: StockMovement[] = [
  {
    id: 'sm-1',
    product_id: 'prd-1',
    product_name: 'Pulpen Standard AE7 0.5mm Hitam',
    type: 'STOCK_IN',
    quantity: 100,
    previous_stock: 0,
    new_stock: 100,
    reference_id: 'PO-INIT-01',
    notes: 'Stok awal pembukaan toko',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'sm-2',
    product_id: 'prd-1',
    product_name: 'Pulpen Standard AE7 0.5mm Hitam',
    type: 'SALE',
    quantity: -1,
    previous_stock: 85,
    new_stock: 84,
    reference_id: 'INV-20260921-001',
    notes: 'Penjualan di Kasir',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'sm-3',
    product_id: 'prd-11',
    product_name: 'Stapler Joyko HD-10 + Isi Staples',
    type: 'DAMAGED',
    quantity: -1,
    previous_stock: 7,
    new_stock: 6,
    reference_id: 'ADJ-001',
    notes: 'Kemasan rusak saat display',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];
